exec-once = hyprctl setcursor catppuccin-mocha-blue-cursors 16

env = XCURSOR_THEME, catppuccin-mocha-blue-cursors 
env = XCURSOR_SIZE, 16
env = HYPRCURSOR_THEME, catppuccin-mocha-blue-cursors
env = HYPRCURSOR_SIZE, 16 
