#source = ~/.config/hypr/themes/frappe.conf
#source = ~/.config/hypr/themes/late.conf
#source = ~/.config/hypr/themes/macchiato.cong
source = ~/.config/hypr/themes/mocha.conf
decoration {
    rounding = 1
    rounding_power = 1
    active_opacity = 1.0
    inactive_opacity = 0.9

    shadow {
        enabled = true
        range = 13
        render_power = 3
        color = $crust
    }

    blur {
        enabled = true
        size = 10
        passes = 1

        vibrancy = 0.1696
    }
}